// "Did you know?" facts for each spread, keyed by book page. Written for an 8-year-old; kept to well-established facts.
window.FACTS = {
  12: ["The universe began about 13.8 billion years ago. The Big Bang wasn't an explosion in space: space itself started stretching out.",
       "The very first stars took around 100 million years to switch on.",
       "Our Sun and Earth formed about 4.6 billion years ago from a spinning cloud of gas and dust."],
  14: ["The first living things were single cells, far too small to see. They lived more than 3.5 billion years ago.",
       "Tiny ocean microbes called cyanobacteria filled the air with oxygen, the gas we breathe.",
       "About 540 million years ago, lots of new animals with shells and eyes appeared. Scientists call it the Cambrian explosion."],
  16: ["Dinosaurs were around for about 165 million years. Humans like us have been here for about 300,000.",
       "T. rex lived closer in time to you than to Stegosaurus!",
       "Birds are living dinosaurs. A chicken is a distant cousin of T. rex."],
  18: ["About 66 million years ago, an asteroid around 10 km (6 miles) wide crashed into what is now Mexico.",
       "Its crater, called Chicxulub, is about 180 km (110 miles) wide, hidden under the ground and the sea.",
       "About three out of every four kinds of living things died out, but some small mammals and birds survived."],
  20: ["Our species, Homo sapiens, first appeared in Africa about 300,000 years ago.",
       "A famous fossil nicknamed Lucy walked on two legs about 3.2 million years ago.",
       "Many people today carry a little Neanderthal DNA, because our ancestors met Neanderthals and had families together."],
  22: ["People started farming about 11,000 years ago in the Middle East, in an area called the Fertile Crescent.",
       "Farming was invented separately in several places, like rice in China and corn in Mexico.",
       "Dogs were tamed even before farming began, more than 15,000 years ago."],
  24: ["Copper was one of the first metals people learned to melt and shape, about 7,000 years ago.",
       "Bronze is copper mixed with a little tin. It's much harder than copper alone.",
       "Ötzi the Iceman, who lived about 5,300 years ago and was found frozen in the Alps, carried a copper axe."],
  26: ["Jericho is one of the oldest towns in the world. People were living there more than 10,000 years ago.",
       "In Çatalhöyük, in Turkey, houses were packed so tightly that people walked across the roofs and climbed in through the top.",
       "Uruk, in Mesopotamia, may have been the world's first big city, with tens of thousands of people about 5,000 years ago."],
  28: ["The wheel was invented about 5,500 years ago, thousands of years after farming began.",
       "The first wheels may have been potter's wheels for shaping clay, not wheels for carts.",
       "The oldest wooden wheel ever found comes from Slovenia and is about 5,100 years old."],
  30: ["The first writing, called cuneiform, was pressed into wet clay with a reed in Mesopotamia about 5,000 years ago.",
       "Early writing was mostly used for counting things like grain, sheep and beer.",
       "Writing was invented separately in Mesopotamia, China and Central America, and probably Egypt too."],
  36: ["Mesopotamia means \"land between the rivers\": the Tigris and the Euphrates, in today's Iraq.",
       "Mesopotamians counted in 60s. That's why an hour has 60 minutes and a circle has 360 degrees.",
       "King Hammurabi of Babylon carved 282 laws onto a tall black stone almost 4,000 years ago."],
  38: ["The Royal Game of Ur is a board game about 4,500 years old. Its rules were found written on a clay tablet.",
       "Egyptians played a board game called senet. Tutankhamun was buried with several senet boards.",
       "Kids in ancient Greece played with yo-yos, spinning tops and knucklebones, a game a bit like jacks."],
  40: ["Tutankhamun became pharaoh of Egypt when he was only about 9 years old.",
       "Making a mummy took about 70 days.",
       "Cleopatra lived closer in time to us than to the building of the Great Pyramid."],
  42: ["The Great Pyramid of Giza was the tallest building in the world for about 3,800 years.",
       "It's made of about 2.3 million stone blocks.",
       "Stonehenge in England is about 5,000 years old. Some of its stones were brought all the way from Wales, about 240 km (150 miles) away."],
  44: ["The Great Sphinx was carved from one huge piece of rock about 4,500 years ago.",
       "It's about 73 meters (240 feet) long, more than twice as long as a blue whale.",
       "Its nose is missing, but Napoleon's soldiers didn't shoot it off. Drawings show it was gone before they arrived."],
  46: ["The Epic of Gilgamesh, from Mesopotamia, is one of the oldest stories ever written down, about 4,000 years old.",
       "Before writing, stories were passed on by memory. Greek poets could recite the Iliad, which has over 15,000 lines.",
       "Aesop's fables, like The Tortoise and the Hare, were told in ancient Greece about 2,500 years ago."],
  48: ["The oldest known jewelry is seashell beads with holes in them, worn more than 100,000 years ago.",
       "Ancient Egyptians loved a deep blue stone called lapis lazuli, carried all the way from mountains in Afghanistan.",
       "Tutankhamun's golden mask is decorated with stripes of blue glass and lapis lazuli."],
  50: ["The first recorded Olympic Games were held in Greece in 776 BCE. The only event was a running race.",
       "Olympic winners got a crown of olive leaves, not a gold medal.",
       "In Central America, people played a ball game with a heavy rubber ball more than 3,000 years ago. No hands allowed!"],
  52: ["Ancient Greece wasn't one country. It was hundreds of city-states, like Athens and Sparta, each with its own rules.",
       "The Parthenon temple in Athens was built about 2,450 years ago for the goddess Athena.",
       "The word \"alphabet\" comes from alpha and beta, the first two letters of the Greek alphabet."],
  54: ["Zero as a real number, one you can add and subtract, was worked out in India about 1,400 years ago.",
       "Our digits 0 to 9 came from India and reached Europe through Arab mathematicians, so they're called Hindu-Arabic numerals.",
       "Over 2,200 years ago, a Greek named Eratosthenes measured the size of the Earth using shadows, and he was close!"],
  56: ["Democracy comes from Greek words meaning \"rule by the people.\" It began in Athens about 2,500 years ago.",
       "In Athens, only free men could vote. Women, enslaved people and foreigners could not.",
       "Athenians could vote to send someone away for 10 years by scratching names on pieces of broken pottery."],
  58: ["The Celts weren't one country. They were many tribes across Europe who spoke related languages.",
       "Celtic languages are still spoken today, including Welsh, Irish, Scottish Gaelic and Breton.",
       "Celtic metalworkers made beautiful gold neck rings called torcs."],
  60: ["The Persian Empire, started by Cyrus the Great about 2,550 years ago, grew to stretch from Egypt to India.",
       "The Persians built the Royal Road, about 2,500 km (1,600 miles) long. Relay riders could carry a message along it in about a week.",
       "Cyrus let many of the peoples he conquered keep their own religions and customs."],
  62: ["Alexander the Great beat the Persian king Darius III at Issus, in what is now Turkey, in 333 BCE.",
       "Alexander was only 23 years old at the time.",
       "When Alexander was a boy, his teacher was the famous philosopher Aristotle."],
  64: ["Philosophy means \"love of wisdom\" in Greek.",
       "Socrates never wrote anything down. We know his ideas from his student Plato.",
       "In China, Confucius taught about kindness, respect and family about 2,500 years ago."],
  66: ["One of the oldest sculptures ever found is the Lion Man, carved from mammoth ivory about 40,000 years ago.",
       "Ancient Greek marble statues were once painted in bright colors. The paint wore off over time.",
       "Michelangelo carved his statue David from a single block of marble. It's over 5 meters (17 feet) tall."],
  68: ["China's first emperor, Qin Shi Huang, was buried with an army of about 8,000 life-size clay soldiers.",
       "The soldiers have different faces and hairstyles, and there are clay horses and chariots too.",
       "Farmers digging a well found the clay army by accident in 1974."],
  70: ["Ancient Egyptians told the time with sundials in the day and water clocks at night.",
       "Clocks with gears first appeared in Europe about 700 years ago, often in church towers.",
       "Towns used to set their clocks by their own noon, so every town had a slightly different time. Railways led to time zones."],
  72: ["At its biggest, the Roman Empire stretched from Britain to Egypt and had about 60 million people.",
       "The Colosseum in Rome could hold about 50,000 people.",
       "The Romans built tens of thousands of miles of stone roads, and some are still used today."],
  74: ["Roman concrete was so strong that the giant dome of the Pantheon in Rome has stood for about 1,900 years.",
       "Aqueducts carried fresh water to Roman cities from miles away, sloping gently so gravity did the work.",
       "Some Roman homes had heated floors, with warm air flowing underneath."],
  76: ["Hinduism is one of the oldest religions still practiced, with roots going back more than 3,000 years.",
       "Buddhism began in India about 2,500 years ago with a teacher called the Buddha.",
       "Judaism, Christianity and Islam all honor Abraham, so they're sometimes called the Abrahamic religions."],
  78: ["Mount Vesuvius erupted in 79 CE and buried the Roman town of Pompeii under ash.",
       "The ash preserved the town so well that we can still see loaves of bread, paintings and writing on the walls.",
       "Vesuvius is still an active volcano, and about 3 million people live near it today."],
  80: ["Diwali, the Hindu festival of lights, is celebrated with lamps, fireworks and sweets.",
       "Chinese New Year has been celebrated for thousands of years. Each year is named after one of 12 animals.",
       "Ancient Romans had a winter festival called Saturnalia, with feasts and gift-giving."],
  82: ["Emperor Ashoka of India's Maurya Empire gave up war after a terrible battle and carved messages of peace on stone pillars.",
       "The four lions from one of Ashoka's pillars are India's national emblem today.",
       "During India's Gupta Empire, the astronomer Aryabhata suggested that the Earth spins."],
  84: ["In 330 CE, Emperor Constantine made a new capital called Constantinople. Today it's Istanbul, in Turkey.",
       "The western half of the Roman Empire ended in 476 CE, but the eastern half lasted almost 1,000 more years.",
       "Hagia Sophia, finished in 537 in Constantinople, was the biggest church in the world for nearly 1,000 years."],
  90: ["China gave the world paper, the compass, gunpowder and printing, known as the Four Great Inventions.",
       "The oldest printed book with a date in it is the Diamond Sutra, printed in China in 868.",
       "The Tang dynasty capital, Chang'an, was one of the biggest cities in the world, with about a million people."],
  92: ["Baghdad's House of Wisdom was a famous center where scholars studied books from Greece, Persia and India.",
       "The word \"algebra\" comes from an Arabic book by the mathematician al-Khwarizmi.",
       "Fatima al-Fihri founded a school in Fez, Morocco, in 859. It's still open, one of the oldest universities in the world."],
  94: ["The Maya built cities with tall stone pyramids and wrote with hundreds of picture-like signs.",
       "The Maya used a symbol for zero more than 1,500 years ago.",
       "The Inca built about 40,000 km (25,000 miles) of roads through the Andes mountains, without wheels or horses."],
  96: ["Tuesday, Wednesday, Thursday and Friday are named after Germanic gods: Tiw, Woden, Thor and Frigg.",
       "The Angles and Saxons moved to Britain about 1,500 years ago. England means \"land of the Angles.\"",
       "At Sutton Hoo in England, a king was buried in a whole ship full of treasure about 1,400 years ago."],
  98: ["The Middle Ages lasted about 1,000 years, from around 500 to 1500.",
       "Most people in medieval Europe were peasants who farmed land owned by a lord.",
       "Monks copied books by hand. One book could take months or even years."],
  100: ["The Battle of Crécy in 1346 was part of the Hundred Years' War between England and France, which actually lasted 116 years.",
        "English archers with longbows could shoot up to 10 arrows a minute.",
        "Later in the same war, a teenage girl named Joan of Arc led French armies."],
  102: ["The Vikings came from Scandinavia: today's Norway, Sweden and Denmark.",
        "Vikings didn't really wear horned helmets. That idea came from costumes in the 1800s.",
        "Leif Erikson sailed to North America about 1,000 years ago, nearly 500 years before Columbus."],
  104: ["The Crusades were a series of wars, starting in 1096, between European Christians and Muslim rulers over Jerusalem and nearby lands.",
        "Jerusalem is a holy city for Jews, Christians and Muslims.",
        "The Muslim leader Saladin was known, even among his enemies, for being fair and keeping his word."],
  106: ["The Khmer Empire, based in today's Cambodia, was one of the most powerful in Southeast Asia about 900 years ago.",
        "Its capital, Angkor, had huge reservoirs and canals to store water for growing rice.",
        "The Srivijaya kingdom, on the island of Sumatra, grew rich by controlling sea trade between India and China."],
  108: ["Angkor Wat, in Cambodia, is the largest religious monument in the world.",
        "It was built about 900 years ago as a Hindu temple and later became a Buddhist one.",
        "Angkor Wat is pictured on Cambodia's flag."],
  110: ["Samurai were warriors in Japan who served powerful lords called daimyo.",
        "Samurai followed a code of honor later called bushido, \"the way of the warrior.\"",
        "Samurai also practiced poetry, handwriting and the tea ceremony, not just fighting."],
  112: ["The first castles were made of wood and earth. Stone castles came later because they were harder to burn.",
        "A moat is a deep ditch, often filled with water, that made it hard for attackers to reach the walls.",
        "Castle toilets were often just holes in the wall with a long drop to the outside!"],
  114: ["Cahokia, near today's St. Louis, was a city of perhaps 10,000 to 20,000 people about 900 years ago.",
        "Cahokia's biggest earth mound, Monks Mound, is about 30 meters (100 feet) tall.",
        "The Ancestral Puebloans built homes into cliffs, like Cliff Palace at Mesa Verde in Colorado."],
  116: ["Polynesian sailors crossed thousands of miles of open ocean in double-hulled canoes, steering by stars, waves and birds.",
        "Polynesians were the first people to reach Hawaii and New Zealand, about 800 years ago or more.",
        "In 1976, the canoe Hōkūleʻa sailed from Hawaii to Tahiti without modern instruments, showing the old ways worked."],
  118: ["Mansa Musa, king of Mali, was one of the richest people who ever lived.",
        "On his trip to Mecca in 1324, Mansa Musa gave away so much gold that its price dropped in Egypt.",
        "Great Zimbabwe was a city with huge stone walls built without any mortar holding the stones together."],
  120: ["The Mongol Empire was the biggest connected land empire in history.",
        "Genghis Khan united the Mongol tribes in 1206.",
        "Mongols lived in round felt tents called gers, or yurts, that they could pack up and move."],
  122: ["One of the oldest known world maps is a Babylonian clay tablet about 2,600 years old.",
        "Old maps often put sea monsters in parts of the ocean nobody had explored.",
        "For about 100 years, many maps wrongly showed California as an island!"],
  124: ["The Black Death spread across Asia, Europe and Africa in the 1340s. It was caused by germs carried by fleas.",
        "The word quarantine comes from the Italian for \"40 days,\" how long ships had to wait before coming ashore.",
        "Nobody knew about germs until the 1800s, so people had many wrong ideas about what caused sickness."],
  126: ["A full suit of plate armor weighed about 15 to 25 kg (30 to 55 pounds), and knights could still run and climb onto a horse.",
        "Chain mail was made of thousands of tiny metal rings linked together.",
        "Samurai armor was made of many small plates laced together with silk cords."],
  132: ["Johannes Gutenberg built a printing press with movable metal letters around 1440.",
        "In Korea, a book was printed with movable metal type even earlier, in 1377.",
        "Before printing, every book was copied by hand, so books were rare and very expensive."],
  134: ["The oldest boat ever found is a dugout canoe from the Netherlands, about 10,000 years old.",
        "Chinese ships were the first to steer with a rudder at the back.",
        "For thousands of years ships were moved by wind or oars. Steam engines took over in the 1800s."],
  136: ["Renaissance means \"rebirth.\" It began in Italy in the 1300s, when people got excited again about ancient Greek and Roman ideas.",
        "Leonardo da Vinci filled notebooks with ideas for flying machines, and he wrote backward, like in a mirror.",
        "Michelangelo spent four years painting the ceiling of the Sistine Chapel in Rome."],
  138: ["Magellan's expedition was the first to sail all the way around the world, from 1519 to 1522.",
        "Of its five ships, only one, the Victoria, made it home. Magellan himself died on the way.",
        "Sailors used a compass, the stars and a tool called an astrolabe to find their way."],
  140: ["Admiral Zheng He led seven huge voyages from China between 1405 and 1433.",
        "His fleet had hundreds of ships, and the biggest \"treasure ships\" may have been much longer than Columbus's ships.",
        "His fleet reached East Africa, and a giraffe was brought back to the Chinese emperor."],
  142: ["Some of the oldest cave paintings, in Indonesia, are more than 45,000 years old.",
        "Before paint came in tubes, artists ground up rocks, plants and even insects to make colors.",
        "The Mona Lisa is quite small, about 77 by 53 cm (30 by 21 inches)."],
  144: ["In 1517, a German monk named Martin Luther wrote 95 arguments against how the Church was doing things, called the 95 Theses.",
        "Thanks to the printing press, Luther's ideas spread across Europe in a few weeks.",
        "The Reformation split Western Christianity and led to the Protestant churches."],
  146: ["Spanish ships carried enormous amounts of silver from mines like Potosí, in today's Bolivia, back to Europe.",
        "Foods from the Americas, like potatoes, tomatoes, corn and chocolate, spread around the world after this time.",
        "Diseases brought from Europe, like smallpox, made millions of Indigenous people sick."],
  148: ["Tenochtitlán, the Aztec capital, was built on an island in a lake, where Mexico City is today.",
        "The Aztecs grew food on chinampas, garden plots built up out of the shallow lake.",
        "Cacao beans, used to make chocolate drinks, were so valuable that the Aztecs used them as money."],
  150: ["The Ottoman Empire lasted more than 600 years, from about 1300 to 1922.",
        "In 1453 the Ottomans captured Constantinople, which became Istanbul.",
        "Coffee houses became popular in the Ottoman Empire in the 1500s and later spread to Europe."],
  152: ["In 1543, Nicolaus Copernicus argued that the Earth goes around the Sun, not the other way around.",
        "In 1610, Galileo used a telescope to discover four moons circling Jupiter.",
        "Astronomers in ancient Babylon kept careful records of the sky for hundreds of years."],
  154: ["The marathon race is named after the Battle of Marathon in 490 BCE. A legend says a runner ran about 40 km (25 miles) to Athens with the news.",
        "At the Battle of Hastings in 1066, William the Conqueror won the crown of England.",
        "The Bayeux Tapestry, about 70 meters (230 feet) long, tells the story of the Battle of Hastings in pictures."],
  156: ["In 1896, Ethiopia defeated an invading Italian army at the Battle of Adwa.",
        "Because of Adwa, Ethiopia stayed independent while almost all of Africa was taken over by European countries.",
        "Empress Taytu, wife of Emperor Menelik II, helped plan the campaign and led soldiers herself."],
  158: ["During the Edo period (1603 to 1868), Japan was ruled by shoguns and was mostly closed to foreigners.",
        "Edo, the shogun's city, grew to over a million people. Today it's called Tokyo.",
        "The famous woodblock print The Great Wave, by Hokusai, was made during this time."],
  160: ["Jamestown, Virginia, founded in 1607, was the first lasting English settlement in North America.",
        "The Mayflower brought the Pilgrims to Plymouth in 1620.",
        "There were 13 British colonies along the Atlantic coast. They became the first 13 US states."],
  162: ["Isaac Newton worked out the laws of motion and gravity. He said watching an apple fall got him thinking.",
        "Newton also showed that white light is made of all the colors of the rainbow.",
        "In the 1670s, Antonie van Leeuwenhoek used his microscopes to see tiny living things in water for the first time."],
  164: ["Harriet Tubman escaped slavery and then went back about 13 times to lead around 70 people to freedom.",
        "The Underground Railroad wasn't a real railroad. It was a secret network of people and safe houses helping enslaved people escape.",
        "Slavery was ended in the United States in 1865 by the 13th Amendment to the Constitution."],
  166: ["The Taj Mahal was built by Emperor Shah Jahan in memory of his wife, Mumtaz Mahal.",
        "About 20,000 workers spent around 20 years building it.",
        "The Mughal emperor Akbar couldn't read, but he had a huge library and had books read aloud to him."],
  168: ["The Forbidden City in Beijing has about 980 buildings and was home to 24 emperors.",
        "Much of the Great Wall you can visit today was rebuilt during the Ming dynasty.",
        "Chinese porcelain was so loved in Europe that people started calling fine dishes \"china.\""],
  170: ["Marie Curie was the first person to win two Nobel Prizes, one in physics and one in chemistry.",
        "Antoine Lavoisier helped show that water is made of hydrogen and oxygen.",
        "Dmitri Mendeleev arranged the elements into the periodic table in 1869 and left gaps for ones nobody had found yet."],
  172: ["Cave paintings and ancient pottery show people dancing thousands of years ago.",
        "Ballet began in the royal courts of Italy and France. King Louis XIV of France loved dancing in ballets himself.",
        "In many cultures dances tell stories, like the hula in Hawaii."],
  174: ["The Golden Age of Piracy lasted from about 1650 to 1730.",
        "Blackbeard was said to tuck slow-burning fuses under his hat to look scary in battle.",
        "Anne Bonny and Mary Read were two famous women pirates."],
  180: ["The Enlightenment was a time in the 1700s when thinkers said people should use reason and ask questions.",
        "Denis Diderot's Encyclopédie tried to collect all human knowledge in 28 big books.",
        "Enlightenment ideas about rights and freedom inspired the American and French Revolutions."],
  182: ["On November 1, 1755, a huge earthquake shook Lisbon, Portugal, followed by a tsunami and fires.",
        "Lisbon was rebuilt with some of the first buildings designed to survive earthquakes.",
        "People who studied the earthquake helped start seismology, the science of earthquakes."],
  184: ["Scientists measure earthquakes with instruments called seismographs.",
        "Krakatoa's eruption in 1883 was so loud it was heard about 4,800 km (3,000 miles) away.",
        "The \"Ring of Fire\" around the Pacific Ocean is where most of the world's earthquakes and volcanoes happen."],
  186: ["The oldest musical instruments ever found are flutes made from bird bones and mammoth ivory, about 40,000 years old.",
        "Mozart wrote his first pieces of music when he was about 5 years old.",
        "Beethoven kept writing music even after he became almost completely deaf."],
  188: ["Peter the Great built a new capital city, St. Petersburg, starting in 1703.",
        "Peter made noblemen shave off their beards, or pay a special beard tax.",
        "Catherine the Great loved art. Her collection became the start of the Hermitage, one of the world's biggest museums."],
  190: ["The Declaration of Independence was approved on July 4, 1776.",
        "Thomas Jefferson wrote the first draft when he was 33.",
        "The American Revolution was fought between the 13 colonies and Britain, from 1775 to 1783."],
  192: ["On Christmas night 1776, George Washington led his army across the icy Delaware River in a snowstorm.",
        "The next morning they surprised the enemy soldiers at Trenton, New Jersey, and won.",
        "The famous painting of the crossing was made 75 years later. In real life, Washington probably didn't stand up in the boat!"],
  194: ["The Industrial Revolution began in Britain in the late 1700s, when machines started doing work people had done by hand.",
        "Steam engines powered factories, trains and ships.",
        "Many children worked long hours in factories and mines. Laws to protect them came later."],
  196: ["Aboriginal and Torres Strait Islander peoples have lived in Australia for more than 50,000 years, maybe 65,000.",
        "They have one of the oldest continuing cultures in the world.",
        "Before 1788, more than 250 different Aboriginal languages were spoken in Australia."],
  197: ["The First Fleet of 11 British ships arrived at Sydney Cove in 1788.",
        "Many of the people on board were convicts, sent from Britain as punishment.",
        "January 26 is Australia Day, but many Aboriginal people call it Invasion Day or Survival Day."],
  198: ["On July 14, 1789, crowds in Paris stormed the Bastille, a fortress used as a prison.",
        "When it was stormed, the Bastille held only seven prisoners.",
        "July 14 is France's national holiday, Bastille Day."],
  200: ["The French Revolution's motto was \"Liberty, Equality, Fraternity.\"",
        "France stopped having a king and became a republic in 1792.",
        "The metric system, with meters and kilograms, was created during the French Revolution."],
  202: ["Alexander Fleming discovered penicillin, the first antibiotic, in 1928 after mold grew on a dish he'd left out.",
        "In the 1840s, doctors started using anesthesia so patients could sleep through surgery.",
        "Doctors only started washing their hands to stop germs in the late 1800s."],
  204: ["Napoleon wasn't actually short. He was about average height for a Frenchman of his time.",
        "Napoleon crowned himself Emperor of the French in 1804.",
        "He was finally defeated at the Battle of Waterloo in 1815."],
  206: ["Long ago, people kept food from spoiling by drying, salting, smoking and pickling it.",
        "Canned food was invented after the French government offered a prize for a way to keep food fresh for its army.",
        "The can opener was invented about 50 years after the can! Before that, people used knives and hammers."],
  208: ["Simón Bolívar helped free six countries from Spanish rule: Venezuela, Colombia, Ecuador, Peru, Bolivia and Panama.",
        "Bolivia is named after Simón Bolívar.",
        "Haiti became independent in 1804, the first country created after enslaved people won their freedom in a revolt."],
  210: ["The first public railway to carry passengers with steam trains opened in England in 1825.",
        "Some people worried that riding a train at 30 mph might be bad for the human body.",
        "The railroad across the United States was finished in 1869 with a golden spike."],
  212: ["Ancient Rome posted daily news on public boards called the Acta Diurna.",
        "One of the first newspapers was printed in Germany in 1605.",
        "The telegraph, invented in the 1840s, let news travel across a country in minutes instead of days."],
  214: ["The word \"engineer\" comes from a Latin word meaning cleverness.",
        "The Brooklyn Bridge, finished in 1883, was the longest suspension bridge in the world when it opened.",
        "Emily Roebling helped finish the Brooklyn Bridge after her husband, the chief engineer, became ill."],
  216: ["About 400,000 people traveled the Oregon Trail, a journey of about 2,000 miles (3,200 km) by covered wagon.",
        "Most pioneers walked beside their wagons instead of riding in them.",
        "The trip usually took four to six months."],
  217: ["As settlers moved west, the US government forced many Native American nations off their lands.",
        "The Cherokee people's forced march west in 1838 is remembered as the Trail of Tears.",
        "Today there are more than 570 federally recognized tribes in the United States."],
  218: ["In 1848, revolutions broke out in about 50 countries and regions of Europe. People called it the Springtime of Peoples.",
        "Many people wanted the right to vote, a free press and fairer working conditions.",
        "France ended slavery in its colonies in 1848."],
  220: ["Charles Darwin sailed around the world for five years on a ship called the Beagle.",
        "Darwin studied finches and giant tortoises on the Galápagos Islands.",
        "Gregor Mendel discovered how traits are passed down by growing thousands of pea plants."],
  222: ["At its largest, about 100 years ago, the British Empire covered about a quarter of the world's land.",
        "People said \"the sun never sets on the British Empire,\" because it was daytime somewhere in it at every hour.",
        "Today 56 countries belong to the Commonwealth, and most were once part of the empire."],
  224: ["The American Civil War was fought from 1861 to 1865 between Northern states, the Union, and Southern states, the Confederacy.",
        "A main cause was slavery. The Union's victory led to the end of slavery in the United States.",
        "Abraham Lincoln's Gettysburg Address, from 1863, is only about 270 words long."],
  226: ["In 1884 and 1885, European leaders met in Berlin and divided up Africa without a single African present.",
        "By 1914, only Ethiopia and Liberia were independent African countries.",
        "Many borders in Africa today were drawn by Europeans, some as straight lines on a map."],
  228: ["Morse code uses dots and dashes. SOS is dot-dot-dot, dash-dash-dash, dot-dot-dot.",
        "Alexander Graham Bell made the first telephone call in 1876: \"Mr. Watson, come here, I want to see you.\"",
        "The first telegraph cable across the Atlantic Ocean was laid along the sea floor in 1858."],
  230: ["The oldest surviving photo taken with a camera was made in France around 1826. It needed hours of light.",
        "Early photos took so long that people had to sit very still, which is one reason they rarely smiled.",
        "The 1888 Kodak camera's slogan was \"You press the button, we do the rest.\""],
  232: ["No two people have the same fingerprints, not even identical twins.",
        "Fingerprints were first used to solve a crime in Argentina in 1892.",
        "Police started using DNA to solve crimes in the 1980s."],
  234: ["The Wright brothers' first flight, in 1903, lasted 12 seconds and went 120 feet (37 meters).",
        "In 1783, the first people ever to fly went up in a hot-air balloon in Paris.",
        "In 1932, Amelia Earhart became the first woman to fly alone across the Atlantic Ocean."],
  236: ["New Zealand was the first country where women could vote in national elections, in 1893.",
        "Women in the United States won the right to vote in 1920.",
        "British suffragettes wore the colors purple, white and green."],
  238: ["Albert Einstein's famous equation, E = mc², shows that a tiny bit of matter holds a huge amount of energy.",
        "Light is the fastest thing there is. In one second it could zip around the Earth about 7 times.",
        "Einstein won the Nobel Prize for explaining how light knocks tiny particles out of metal, the idea behind solar panels."],
  240: ["Karl Benz built the first real gasoline car in 1885. It had three wheels.",
        "In 1888, Bertha Benz took the first long car trip, about 100 km (65 miles), and bought fuel at a pharmacy.",
        "Henry Ford's assembly line made cars cheaper. About 15 million Model T Fords were built."],
  242: ["Roald Amundsen's team reached the South Pole first, on December 14, 1911, using dog sleds.",
        "Ernest Shackleton's ship Endurance was crushed by ice in 1915, yet all 28 of his men survived.",
        "Tenzing Norgay and Edmund Hillary were the first to climb to the top of Mount Everest, in 1953."],
  244: ["The Titanic sank on its very first voyage, in April 1912, after hitting an iceberg.",
        "The wreck was found in 1985, about 3,800 meters (12,500 feet) under the sea.",
        "There weren't enough lifeboats for everyone, so the rules for ships were changed afterward."],
  250: ["World War I lasted from 1914 to 1918 and involved countries from all over the world.",
        "Soldiers fought from long ditches called trenches.",
        "The fighting stopped at 11 a.m. on November 11, 1918, so many countries remember the war every November 11."],
  252: ["The 1920s are called the Roaring Twenties because of the new music, dances and fun after World War I.",
        "Jazz became hugely popular, with stars like Louis Armstrong.",
        "In 1927, Charles Lindbergh flew alone, nonstop, from New York to Paris in about 33 and a half hours."],
  253: ["During the Great Depression in the 1930s, millions of people lost their jobs.",
        "In the Dust Bowl, giant dust storms blew across the farms of the US Great Plains.",
        "Movies helped people forget their troubles. The Wizard of Oz came out in 1939."],
  254: ["Howard Carter found Tutankhamun's tomb in 1922, still full of treasure.",
        "Archaeologists love old trash, because what people threw away shows how they lived.",
        "The Rosetta Stone had the same message in three scripts, which helped people read Egyptian hieroglyphs again."],
  256: ["The Soviet Union was formed in 1922 and was the biggest country in the world.",
        "It broke apart in 1991 into 15 separate countries, including Russia and Ukraine.",
        "In 1957, the Soviet Union launched Sputnik, the first satellite to circle the Earth."],
  258: ["The 10-story Home Insurance Building in Chicago, built in 1885, is often called the first skyscraper.",
        "Safe elevators made tall buildings possible. Elisha Otis showed off his elevator safety brake in 1854.",
        "The Burj Khalifa in Dubai is about 828 meters (2,717 feet) tall, the tallest building in the world."],
  260: ["World War II lasted from 1939 to 1945 and was the biggest war in history.",
        "British Prime Minister Winston Churchill gave famous speeches that helped keep people brave.",
        "Codebreakers at Bletchley Park in England cracked secret German messages made with the Enigma machine."],
  262: ["During World War II, foods like sugar, butter and meat were rationed, so each family got only a set amount.",
        "People grew vegetables in \"victory gardens\" in their yards and in parks.",
        "Millions of women took factory jobs, and \"Rosie the Riveter\" became their symbol."],
  264: ["Anne Frank was a Jewish girl who hid with her family in secret rooms in Amsterdam for more than two years.",
        "Anne's diary was published after the war and has been read by millions of people around the world.",
        "Brave helpers like Miep Gies risked their lives to bring the hidden families food and news."],
  266: ["On June 6, 1944, Allied soldiers landed on beaches in Normandy, France.",
        "It was the biggest invasion from the sea in history, with about 7,000 ships and boats.",
        "The beaches had code names: Utah, Omaha, Gold, Juno and Sword."],
  268: ["The United States joined World War II after Japan attacked Pearl Harbor, Hawaii, on December 7, 1941.",
        "At the Battle of Midway in 1942, the US Navy sank four Japanese aircraft carriers.",
        "Navajo Code Talkers sent secret messages in their own language, and the code was never broken."],
  270: ["India became independent from Britain on August 15, 1947.",
        "In 1930, Gandhi led the Salt March, walking about 385 km (240 miles) to protest an unfair British law.",
        "Gandhi believed in protesting without violence."],
  271: ["Ghana became independent from Britain in 1957, one of the first African colonies to do so.",
        "1960 is called the Year of Africa, because 17 African countries became independent that year.",
        "Nelson Mandela spent 27 years in prison and then became South Africa's first Black president, in 1994."],
  272: ["Julius Caesar sent secret messages using a code that shifted every letter a few places along the alphabet.",
        "During the American Revolution, the Culper Spy Ring used invisible ink to send messages to George Washington.",
        "Spies have even strapped tiny cameras to pigeons to take photos from the air."],
  274: ["The Middle East sits where Asia, Africa and Europe meet.",
        "It's where Judaism, Christianity and Islam began.",
        "A lot of the world's oil comes from the Middle East."],
  276: ["Before refrigerators, many families kept food cold with blocks of ice delivered by an iceman.",
        "Electric washing machines first appeared in the early 1900s.",
        "The microwave oven was invented after an engineer noticed a radar machine had melted a candy bar in his pocket."],
  278: ["People have used wind to turn windmills and push sailing ships for hundreds of years.",
        "Enough sunlight hits the Earth in about an hour and a half to power the whole world for a year.",
        "The Three Gorges Dam in China, which makes electricity from flowing water, is the world's biggest power station."],
  280: ["The Korean War was fought from 1950 to 1953 between North Korea and South Korea, with other countries helping each side.",
        "The fighting stopped with an agreement called an armistice, but no peace treaty was ever signed.",
        "A strip of land called the DMZ still separates North and South Korea."],
  281: ["The Vietnam War lasted from about 1955 to 1975.",
        "It's often called the first \"television war,\" because people saw it on the news at home every night.",
        "Vietnam became one country again in 1976."],
  282: ["In 1963, Martin Luther King Jr. gave his \"I Have a Dream\" speech in Washington, D.C.",
        "In the 1960s, the Beatles became the most famous band in the world.",
        "In 1969, astronauts walked on the Moon for the very first time."],
  284: ["Africa has 54 countries, more than any other continent.",
        "More than 2,000 languages are spoken in Africa.",
        "Nigeria has the most people of any African country, more than 200 million."],
  286: ["The Cold War was a long rivalry between the United States and the Soviet Union, from about 1947 to 1991.",
        "It was called \"cold\" because the two superpowers never fought each other directly.",
        "The Berlin Wall divided the city of Berlin from 1961 until people tore it down in 1989."],
  288: ["In 1961, Yuri Gagarin of the Soviet Union became the first person to travel into space.",
        "In 1963, Valentina Tereshkova became the first woman in space.",
        "In 1961, President Kennedy promised that America would land a person on the Moon before 1970."],
  290: ["Neil Armstrong and Buzz Aldrin landed on the Moon on July 20, 1969, while Michael Collins circled above.",
        "The Saturn V rocket that carried them was taller than the Statue of Liberty.",
        "The astronauts' footprints are still on the Moon, because there's no wind to blow them away."],
  292: ["In October 1962, the United States found Soviet nuclear missiles in Cuba, just 90 miles (145 km) from Florida.",
        "For 13 days the world worried about war, until both sides agreed to remove missiles.",
        "Afterward, a hotline was set up so the US and Soviet leaders could talk to each other directly."],
  294: ["In 1955, Rosa Parks refused to give up her bus seat, which started the Montgomery Bus Boycott.",
        "In 1960, 6-year-old Ruby Bridges became the first Black child at her all-white school in New Orleans.",
        "The Civil Rights Act of 1964 made it illegal to treat people unfairly because of their race."],
  296: ["Silk was invented in China thousands of years ago, from the cocoons of silkworms.",
        "Blue jeans were invented in 1873 by Levi Strauss and Jacob Davis, as tough work pants.",
        "In the 1700s, fashionable European men wore powdered wigs and high-heeled shoes."],
  298: ["Voyager 1, launched in 1977, is the farthest human-made object, more than 24 billion km (15 billion miles) away.",
        "The International Space Station circles the Earth about 16 times a day.",
        "In 2021, a little helicopter called Ingenuity made the first powered flight on another planet: Mars."],
  300: ["China and India each have more than 1.4 billion people.",
        "In 2023, India passed China to become the country with the most people.",
        "Shanghai, in China, has the busiest container port in the world."],
  302: ["One early computer, ENIAC, built in 1945, filled a whole room and weighed about 27 tonnes (30 tons).",
        "Ada Lovelace wrote what many call the first computer program in the 1840s, for a machine that was never finished.",
        "In 1947, a real moth was found stuck inside a computer, and the team taped it into their logbook as the first actual \"bug.\""],
  304: ["Louis Braille invented his raised-dot reading system when he was just 15.",
        "Each braille letter is made from a cell of up to six dots, which can make 64 different patterns.",
        "Hearing aids used to be big horn-shaped ear trumpets. Now some are small enough to fit inside the ear."],
  306: ["In 1848, the Seneca Falls Convention in New York was the first big US meeting about women's rights.",
        "In 1972, a law called Title IX made it illegal for US schools to treat girls unfairly, including in sports.",
        "Malala Yousafzai won the Nobel Peace Prize at 17 for standing up for girls' right to go to school."],
  308: ["The internet began as ARPANET. Its first message, in 1969, crashed the computer after two letters: \"LO.\"",
        "Tim Berners-Lee invented the World Wide Web in 1989.",
        "Most internet data crosses oceans through cables lying on the sea floor."],
  310: ["The word \"teenager\" only became common in the 1940s.",
        "In the 1950s, rock 'n' roll became the music of teenagers.",
        "Skateboarding started in California in the 1950s, when surfers wanted something to ride on land."],
  312: ["The word \"robot\" comes from a 1920 Czech play. It comes from a word meaning forced work.",
        "The first factory robot, Unimate, started work in a car factory in 1961.",
        "Robot rovers explore Mars for us, like Perseverance, which landed in 2021."],
  314: ["Edward Jenner made the first vaccine in 1796, against smallpox, using a milder disease called cowpox.",
        "The word vaccine comes from vacca, the Latin word for cow.",
        "Thanks to vaccines, smallpox was wiped out completely, declared gone in 1980."],
  316: ["Queen Elizabeth II reigned for 70 years, longer than any other British monarch.",
        "William the Conqueror became king of England in 1066.",
        "King Charles III was crowned in 2023."],
  318: ["George Washington was the first US president, and he's the only one who never lived in the White House.",
        "The teddy bear is named after President Theodore \"Teddy\" Roosevelt.",
        "Abraham Lincoln was the tallest president, at 6 feet 4 inches (193 cm)."],
};
